services:
  db:
    container_name: postgres
    image: postgres:16.4
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: codeguard
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
  backend-api:
    container_name: code-guard-api
    image: lyubomir15/code-guard-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/codeguard
    ports:
      - "8088:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: