spring:
  application:
   name: CodeGuard
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 9100

application:
  basicauth:
    username: user
    password: pass
    swagger:
      username: admin
      password: pass
  cors:
    allowed:
      - http://localhost:3000
  management:
    server:
      port: 9101
    endpoints:
      web:
        exposure:
          include:
            - health
            - info
            - prometheus
  clamav:
    enabled: false
    host: localhost
    port: 3310
    timeout: 30000
  openai:
    token: "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"
    model: "gpt-4o"
    maxTokens: 128_000
    maxOutputTokens: 16_384
    connectionDuration: 200

springdoc:
  swagger-ui:
    path: /swagger