spring:
  application:
   name: CodeGuard
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: jdbc:postgresql://localhost:5332/codeguard
    username: username
    password: secret123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: codeguard
    show-sql: true
  liquibase:
    enabled: true
    url: jdbc:postgresql://localhost:5332/codeguard
    default-schema: codeguard
    change-log: classpath:db/changelog/changelog.sql
    driver-class-name: org.postgresql.Driver
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  docker:
    compose:
      enabled: false

server:
  port: 8080

application:
  basicauth:
    username: admin
    password: pass
    swagger:
      username: user
      password: pass
  cors:
    allowed:
      - http://localhost:3000
  management:
    endpoints:
      web:
        exposure:
          include: "*"
  clamav:
    enabled: false
    host: localhost
    port: 3310
    timeout: 30000
  openai:
    token: "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"
    model: "gpt-4o"
    maxTokens: 128_000
    maxOutputTokens: 16_384
    connectionDuration: 200

springdoc:
  swagger-ui:
    path: /swagger