name: CI - Build Backend

on:
  pull_request:
    branches:
      - main
    paths:
      - src/**

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17.4
        env:
          POSTGRES_USER: ${{ secrets.DATASOURCE_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.DATASOURCE_PASSWORD }}
          POSTGRES_DB: codeguard
        ports:
          - 5332:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: Wait for database to start
        run: sleep 15
      - name: Build and run Unit Tests with Gradle
        run: ./gradlew check --no-daemon --console=plain
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5332/codeguard
          SPRING_DATASOURCE_USERNAME: ${{ secrets.DATASOURCE_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.DATASOURCE_PASSWORD }}
          SPRING_LIQUIBASE_ENABLED: "false"
          SPRING_JPA_HIBERNATE_DDL_AUTO: "create-drop"